services:
  - type: web
    name: vans-brnd
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false # You will need to set this in the Render Dashboard (e.g., using MongoDB Atlas)
